### ISSUE TITLE
Download a Truffle platform and try to run some example

### ISSUE THREAD

**Issue by w0ckeezz** [kosyachniy/mercari#4]
https://truffleframework.com/
https://github.com/trufflesuite/truffle

**Comment by w0ckeezz** [comment]
Pet-shop project is downloaded

**Comment by w0ckeezz** [comment]
Error with trying to unbox the project (any project on Truffle):

Error: Error making request to https://raw.githubusercontent.com/truffle-box/bare-box/master/truffle.js. Got error: self signed certificate in certificate chain. Please check the format of the requested resource.
    at Request._callback 
    at self.callback 
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError 
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)

**Comment by w0ckeezz** [comment]
The same issue: https://github.com/trufflesuite/truffle/issues/766

**Comment by w0ckeezz** [comment]
The issue have overcome by installing the resos manualy

**Comment by w0ckeezz** [comment]
Pet shop is ran
